## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [ ]:
# YOUR WORK HERE
!wget 'https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip'

--2020-06-09 20:59:44--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.1s    

2020-06-09 20:59:44 (154 KB/s) - ‘student.zip’ saved [20478/20478]



In [ ]:
!unzip student.zip

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [ ]:
#Import libraries
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
#create the dataframe for student-mat.csv
df = pd.read_csv('student-mat.csv', sep=';')
print(df.shape)
df.head()

(395, 33)


school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [ ]:
# YOUR WORK HERE
#Run chi2 tests on the two variables 'internet' and 'failures'
cont_table = pd.crosstab(df['failures'], df['internet'])

cont_table

internet  no  yes
failures         
0         47  265
1         13   37
2          2   15
3          4   12

In [ ]:
#Run the chi2 to determine whether or not these variables are associated with each other
chi2, p_value, dof, expected = stats.chi2_contingency(cont_table)

print('chi2 statistic:', chi2)
print('p value: ', p_value)
print('degress of freedom: ', dof)
print('expected frequencies table: ', expected)

chi2 statistic: 4.796825454131461
p value:  0.18729362004759023
degress of freedom:  3
expected frequencies table:  [[ 52.13164557 259.86835443]
 [  8.35443038  41.64556962]
 [  2.84050633  14.15949367]
 [  2.67341772  13.32658228]]


In [ ]:
#Run chi2 tests on the two variables 'Pstatus' and 'famrel'
cont_table = pd.crosstab(df['school'], df['address'])

cont_table

address   R    U
school          
GP       63  286
MS       25   21

In [ ]:
#Run the chi2 to determine whether or not these variables are associated with each other
chi2, p_value, dof, expected = stats.chi2_contingency(cont_table)

print('chi2 statistic:', chi2)
print('p value: ', p_value)
print('degress of freedom: ', dof)
print('expected frequencies table: ', expected)

chi2 statistic: 28.862399672679885
p value:  7.77068354957483e-08
degress of freedom:  1
expected frequencies table:  [[ 77.75189873 271.24810127]
 [ 10.24810127  35.75189873]]


###Conclusions

 - **Two pairs of variables that are dependent (are associated with one another).**

- - With a Chi^2 statistic of 28.86, and a p_value of 7.77e-08, we can say that the variables `school` and `address` are associated with each other.


 - **Two pairs of variables that are independent (have no significant relationship).**
 
 - - With a Chi^2 statistic of 4.80, and a p_value of 0.19, we can say that the variables `internet` and `failures` are not associated with each other

**Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another?** 

- - It makes intuitive sense that the school a student attends is associated with their address, since location can often play a role in school decisions.

- - It does not make intuitive sense that a students internet status is not associated with failures, as lack of access to internet could create more hurdles for students to study and access resources online for learning. 

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [ ]:
# YOUR WORK HERE
#Create a crosstab of the two variables, famsize and address
observed = pd.crosstab(df['famsize'], df['address'])

observed = observed.values

observed

array([[ 68, 213],
       [ 20,  94]])

In [ ]:
# (row_total)(column_total) / sample_size
row_total = df['address'].value_counts().sort_index().values
row_total

array([ 88, 307])

In [ ]:
column_total = df['famsize'].value_counts().sort_index().values
column_total

array([281, 114])

In [ ]:
sample_size = df.shape[0]
sample_size

395

In [ ]:
expected = np.array([[0,0],
                    [0,0]])

for i, col in enumerate(column_total):
  for j, row in enumerate(row_total):
    expected_value = row*col / sample_size
    expected[i][j] = expected_value


expected

array([[ 62, 218],
       [ 25,  88]])

In [ ]:
observed

array([[ 68, 213],
       [ 20,  94]])

In [ ]:
#Calculate the chi^2 statistic
((observed - expected)**2 / expected).sum().sum()

2.1044149694638006

In [ ]:
#Check using scipy
check_chi2('famsize', 'address')

chi2 statistic: 1.7080569422911414
p value:  0.19123766649306323
degress of freedom:  1
expected frequencies table:  [[ 62.60253165 218.39746835]
 [ 25.39746835  88.60253165]]


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE
#Create a function that will take two variables(columns), run the chi2 test, and print out the results

def check_chi2(var1, var2):
  #Create the contingency table
  cont_table = pd.crosstab(df[var1], df[var2])

  #Run the Chi^2 test on the contingency table
  chi2, p_value, dof, expected = stats.chi2_contingency(cont_table)
  print('chi2 statistic:', chi2)
  print('p value: ', p_value)
  print('degress of freedom: ', dof)
  print('expected frequencies table: ', expected)

In [ ]:
#Run and test the method, using two different variables

check_chi2('higher', 'failures')

chi2 statistic: 45.21014899446959
p value:  8.348431490698966e-10
degress of freedom:  3
expected frequencies table:  [[ 15.79746835   2.53164557   0.86075949   0.81012658]
 [296.20253165  47.46835443  16.13924051  15.18987342]]




### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- **What is a sample "estimate" in statistics?**

- - A sample estimate of how closely a sample of data is representative of the larger population from which the sample is collected from. 

- **What are hypothesis test? How are they useful?**

- - Hypothesis tests are used to determine whether or not to accept or reject a statistical hypothesis, using a null hypothesis, which assumps that sample observations dervice purely from chance, and an alternative hypothesis, which assumes that sample observations are influenced by non-random causes.

- **What is a "null hypothesis?"**

- - A Null Hypothesis is teh hypothesis that sample observations result purely from chance

- **What is a p-value and what does it represent?**

- - A p-value is the probability that the sample obvservation is random, rather than driven by causal factors.

- **What does it mean for something to be "statistically significant?"**

- - Something has statistical significane when it has a very low probablity of occuring, typically lower than 5%, given the null hypothesis. 

- **What is a test statistic and how does it relate to a p-value?**

- - The t-statistic is the degree to which the estimated value of a parameter differs from the hypothesized value, measured in standard deviation.  

- **What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?**

- - "Degrees of freedom" is the number of values that are free to vary in the final calculation.  

- - *1-sample dof* - To calculate dof for a 1-sample test: n - 1

- - *2-sample dof* - To calculate dof for a 2-sample test: (n1 + n2) - 2

- - *chi^2 test* - To caulcuate dof for a chi^2 test:  n - 1

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)